### ISSUE TITLE
which can be heavily compressed to about 2 bytes per part is not correct. it shoud be 4 bytes per part.

### ISSUE THREAD

**Issue by zjuchenwei** [cgtuebingen/Product-Quantization-Tree#14]
In your paper , you mentioned that information of line-quantization  can be heavily compressed to about 2 bytes per part. I think that's not correct , because in your code you use a float which means 4 bytes to store the information per part. 2 bytes for the indices of the centroids and 2 bytes for the lambda.

**Comment by PatWie** [comment]
For the Sift1M it only needs to be 2 bytes, see our lambda quantization and c1<16, c2<16. For Sift1B it would be 3 bytes theoretically but the implementation uses 4 bytes.
