### ISSUE TITLE
GPUassert: invalid argument

### ISSUE THREAD

**Issue by HulkSun** [cgtuebingen/Product-Quantization-Tree#2]
Hi,
I am trying to create a database using this shell
`./build/tool_createdb -dataset workdir/sift/base.umem -device 1 
`
then I get this wrong massage: 
`GPUassert: invalid argument /Product-Quantization-Tree/tool_createdb.cpp 113
`
and this is the code that goes wrong:
`  SAFE_CUDA_CALL(cudaMemcpy(chLines,     ppt.getLine(),      FLAGS_chunksize * FLAGS_lineparts * sizeof(float), cudaMemcpyDeviceToHost));
` 
how can I deal with this?
Thanks!

**Comment by HulkSun** [comment]
Problem solved!
I removed the _SAFE_CUDA_CALL()_, then it works!
specifically:
`  //SAFE_CUDA_CALL(cudaMemcpy(chLines,     ppt.getLine(),      FLAGS_chunksize * FLAGS_lineparts * sizeof(float), cudaMemcpyDeviceToHost));
  cudaMemcpy(chLines,ppt.getLine(),FLAGS_chunksize*FLAGS_lineparts*sizeof(float),cudaMemcpyDeviceToHost);
  `
weried!

**Comment by HulkSun** [comment]
I think maybe the data size is too large to transfer from GPU to memory, so I transfer this data partly and it works.

```

 // SAFE_CUDA_CALL(cudaMemcpy(chLines,     ppt.getLine(),      FLAGS_chunksize * FLAGS_lineparts * sizeof(float), cudaMemcpyDeviceToHost));

  if (FLAGS_chunksize * FLAGS_lineparts < 100000000/4) 
  {  
      SAFE_CUDA_CALL(cudaMemcpy(chLines,     ppt.getLine(),      FLAGS_chunksize * FLAGS_lineparts * sizeof(float), cudaMemcpyDeviceToHost));
  } 
  else 
  {
      uint chunk = 100000000/4;
      int chunks = FLAGS_chunksize * FLAGS_lineparts / chunk;
	  cout << "chunks :  " << chunks << endl;
      for (int c = 0; c < chunks; c++) 
	  {
          cudaMemcpy(chLines + c * chunk, ppt.getLine() + c * chunk, chunk * sizeof(float), cudaMemcpyDeviceToHost);
      }
  }
```

**Comment by PatWie** [comment]
Which GPU do you use?

**Comment by HulkSun** [comment]
CUDA v8.0, GCC 4.9.4 on Ubuntu 14.04,  Nvidia Titan X

**Comment by HulkSun** [comment]
I was wrong!
I forget to add `SAFE_CUDA_CALL( )` to  `cudaMemcpy( )`, and after I added it ,I get the same error `GPUassert: invalid argument`.

**Comment by PatWie** [comment]
Cannot reproduce it here. Feel free to re-open.
