### ISSUE TITLE
A confusion about the variable 'data_num' in tool_createdb.cpp.

### ISSUE THREAD

**Issue by HulkSun** [cgtuebingen/Product-Quantization-Tree#4]
Hi,
the variable `data_num`  in tool_createdb.cpp at line 87, it is computed by dividing by  `FLAGS_chunksize` and then multiplying by `FLAGS_chunksize'.
```
  const uint chunkMax = DataReader.num() / FLAGS_chunksize;
  const uint data_num = chunkMax * FLAGS_chunksize;
```
and the result of this computing is _data_num  = 0_.
is it right to calculate in this way ?
Why not using  `DataReader.num()` directly like `data_num  = DataReader.num()`?

**Comment by PatWie** [comment]
This GIT contains the code we ran our experiments. Event after a bit of polishing there are some dead code parts which were only used to test some ideas.
