### ISSUE TITLE
cpu_version

### ISSUE THREAD

**Issue by zjuchenwei** [cgtuebingen/Product-Quantization-Tree#5]
When i use the same code ,same parameter and the same dataset, but i get a very low recall value.I don't know why

**Comment by PatWie** [comment]
Did you change all lines [here](https://github.com/cgtuebingen/Product-Quantization-Tree/blob/master/cpu_version/tools/build_db.cpp#L10-L16), [here](https://github.com/cgtuebingen/Product-Quantization-Tree/blob/master/cpu_version/tools/build_tree.cpp#L10-L16) and [here](https://github.com/cgtuebingen/Product-Quantization-Tree/blob/master/cpu_version/tools/query.cpp#L10-L15)?

**Comment by zjuchenwei** [comment]
const uint D = 128;   // dimension of vector
      const uint P = 2;     // number of parts
      const uint C1 = 8;   // number of clusters in 1st level per part
      const uint C2 = 4;    // number of refinements
      const uint H1 = 4;
     const uint RE = 32;
yes，the above is my settings. as mentioned in your article,  (8*4)^2

**Comment by zjuchenwei** [comment]
dim:                        128
num:                        100000
time to insert db           158480ms
lambda range      -159.006 to 212.475
avg. quant error  40.042
min. quant error  83.3653
max. quant error  4058.38
query-set                   /root/Product-Quantization-Tree-master/workdir/sift/query.umem
dim:                        128
num:                        10000
truth-set                   /root/Product-Quantization-Tree-master/workdir/sift/groundtruth.imem
dim:                        100
num:                        10000
candidate list:             20820.6
bin list:                   0
@R1: 0
@R10: 0
@R100: 0
@R1000: 0.0007
@R10000: 0.011
@R100000: 0.0229
avg. query time   26.5368ms
total. query time 265s
as you see, the difference of the recall is quite obvious. please tell me where i am wrong.

**Comment by PatWie** [comment]
Unfortunately, I cannot reproduce this error. I get

![0](https://cloud.githubusercontent.com/assets/6756603/26303244/47b7796e-3ee7-11e7-9d08-368eaf9ac73f.png)

even after a fresh git clone

**Comment by zjuchenwei** [comment]
can you give me your settings?  and do you have special configuration?

**Comment by zjuchenwei** [comment]
can you offer me these files? 
build_db.cpp,
build_tree.cpp
query.cpp
learn.umem
is that enough to reproduce your experiment?

**Comment by zjuchenwei** [comment]
root@slave2:~/pq_cpu_version1/build# ../tools/run.sh 
dim:                        128
num:                        100000
C1:                        8
C2:                        4
H1:                        4
RE:                        32
learn-set                   /root/Product-Quantization-Tree-master/workdir/sift/learn.umem
C1:                        8
C2:                        4
H1:                        4
RE:                        32
db-set                   /root/Product-Quantization-Tree-master/workdir/sift/base.umem
time to insert db           6578ms
lambda range      -115.263 to 154.247
avg. quant error  39.0472
min. quant error  83.2203
max. quant error  3990.01
C1:                        8
C2:                        4
H1:                        4
RE:                        32
query-set                   /root/Product-Quantization-Tree-master/workdir/sift/query.umem
dim:                        128
num:                        10000
truth-set                   /root/Product-Quantization-Tree-master/workdir/sift/groundtruth.imem
dim:                        100
num:                        10000
candidate list:             20822.4
bin list:                   0
@R1: 0
@R10: 0
@R100: 0
@R1000: 0.0011
@R10000: 0.0108
@R100000: 0.0229
avg. query time   4.2927ms
total. query time 42s
root@slave2:~/pq_cpu_version1/build# 
i also get the fresh git clone and just add some output to identify my settings, but the result is stiil the same

**Comment by zjuchenwei** [comment]
dim:                        128
num:                        100000
C1:                        16
C2:                        8
H1:                        8
RE:                        32
learn-set                   /root/Product-Quantization-Tree-master/workdir/sift/learn.umem
C1:                        16
C2:                        8
H1:                        8
RE:                        32
db-set                   /root/Product-Quantization-Tree-master/workdir/sift/base.umem
time to insert db           23863ms
lambda range      -115.51 to 100.888
avg. quant error  1.35079
min. quant error  1.16343
max. quant error  191.936
C1:                        16
C2:                        8
H1:                        8
RE:                        32
query-set                   /root/Product-Quantization-Tree-master/workdir/sift/query.umem
dim:                        128
num:                        10000
truth-set                   /root/Product-Quantization-Tree-master/workdir/sift/groundtruth.imem
dim:                        100
num:                        10000
candidate list:             20014.8
bin list:                   0
@R1: 0
@R10: 0
@R100: 0
@R1000: 0.001
@R10000: 0.0112
@R100000: 0.021
avg. query time   4.5569ms
total. query time 45s

**Comment by zjuchenwei** [comment]
why the difference is so huge, i can not even get close.

**Comment by PatWie** [comment]
Sharing the compiled version is not possible because of these hard-coded paths. The difference in the quantization error is the first spot where I would look into. Your quantization error seems to be wrong.

**Comment by zjuchenwei** [comment]
can you give a personal email，which i can send you my data-set or source.

**Comment by zjuchenwei** [comment]
![20170524003239](https://cloud.githubusercontent.com/assets/4024185/26364928/a2c382da-4018-11e7-9586-911c77d71440.png)
my matab runs perfect，but my c program still has problem but still thank you very much！！！！

**Comment by zjuchenwei** [comment]
![20170524015923](https://cloud.githubusercontent.com/assets/4024185/26368603/a86e0de8-4024-11e7-9480-f833b40de762.png)
finally solve the problem, you definitely have a bug in your code! but still thank you for your help

**Comment by PatWie** [comment]
The values of your screenshot look good!
> finally solve the problem, you definitely have a bug in your code
Which line, you are thinking is not correct?

**Comment by zjuchenwei** [comment]
when you load the dataset ,change all the    
    "memiterator<float, uint8_t>" to memiterator<float, float>"
