### ISSUE TITLE
sift1m has 10^6 vectors ,how do you use the first 2^12 vectors from (64*8)^6 bins,

### ISSUE THREAD

**Issue by zjuchenwei** [cgtuebingen/Product-Quantization-Tree#8]
what's your configuration to p ,k1,k2,w and pline to get 0.51 recall in 0.02ms.
and what's the type of your gpu

**Comment by zjuchenwei** [comment]
![image](https://user-images.githubusercontent.com/4024185/27636323-89674ede-5c3d-11e7-8e9f-28fedb6703fc.png)

![image](https://user-images.githubusercontent.com/4024185/27636337-aa3c1fc2-5c3d-11e7-8537-36125e166a48.png)
and my w=8

**Comment by PatWie** [comment]
The 4096 is simply a constraint (of sorting) and we used the old NVIDIA GTX Titan X for the experiments (like we wrote in the paper).
